-- Create email_templates table for centralized email management
CREATE TABLE public.email_templates (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  template_key TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  subject TEXT NOT NULL,
  body_html TEXT NOT NULL,
  variables JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  last_sent_at TIMESTAMP WITH TIME ZONE,
  send_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Admins can manage email templates"
ON public.email_templates
FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Anyone can view active templates"
ON public.email_templates
FOR SELECT
USING (is_active = true);

-- Trigger for updated_at
CREATE TRIGGER update_email_templates_updated_at
BEFORE UPDATE ON public.email_templates
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert default email templates
INSERT INTO public.email_templates (template_key, category, name, description, subject, body_html, variables) VALUES

-- Conta e Segurança
('password_reset', 'account_security', 'Recuperação de Senha', 'Enviado quando o usuário solicita recuperação de senha', 'Redefinição de Senha - Camaleão Ecoturismo', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#820AD1 0%,#6B08A8 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">🔐 Recuperação de Senha</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">Camaleão Ecoturismo</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Recebemos uma solicitação para redefinir sua senha. Clique no botão abaixo para criar uma nova senha:</p><div style="text-align:center;margin:30px 0;"><a href="{{reset_link}}" style="background:#820AD1;color:white;padding:16px 32px;text-decoration:none;border-radius:8px;font-weight:600;display:inline-block;">Redefinir Senha</a></div><p style="color:#999;font-size:14px;">Este link expira em 1 hora. Se você não solicitou esta alteração, ignore este e-mail.</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p><p style="color:rgba(255,255,255,0.7);margin:8px 0 0 0;font-size:13px;">Transformando cada viagem em uma aventura inesquecível</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do usuário", "example": "João Silva"}, {"key": "reset_link", "label": "Link de redefinição", "example": "https://..."}]'),

('admin_2fa_code', 'account_security', 'Código 2FA Admin', 'Código de verificação em duas etapas para login admin', '🔐 Código de Verificação - Camaleão Admin', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#820AD1 0%,#6B08A8 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">🔐 Código de Verificação</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">Área Administrativa</p></td></tr><tr><td style="padding:40px;text-align:center;"><p style="color:#666;line-height:1.6;">Use o código abaixo para acessar o painel administrativo:</p><div style="background:#f8f0ff;border:2px solid #820AD1;border-radius:12px;padding:20px;margin:20px 0;"><span style="font-size:36px;font-weight:700;letter-spacing:8px;color:#820AD1;">{{code}}</span></div><p style="color:#999;font-size:14px;">Este código expira em {{expiry_minutes}} minutos.</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "code", "label": "Código 2FA", "example": "123456"}, {"key": "expiry_minutes", "label": "Minutos até expirar", "example": "10"}]'),

('account_created', 'account_security', 'Conta Criada', 'Boas-vindas ao criar conta no portal do cliente', 'Bem-vindo(a) à Camaleão Ecoturismo! 🦎', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#820AD1 0%,#6B08A8 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">🦎 Bem-vindo(a)!</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">Camaleão Ecoturismo</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Sua conta foi criada com sucesso! Agora você pode:</p><ul style="color:#666;line-height:1.8;"><li>Acompanhar suas reservas</li><li>Acumular pontos de fidelidade</li><li>Conquistar selos exclusivos</li><li>Receber ofertas especiais</li></ul><div style="text-align:center;margin:30px 0;"><a href="{{portal_link}}" style="background:#820AD1;color:white;padding:16px 32px;text-decoration:none;border-radius:8px;font-weight:600;display:inline-block;">Acessar Minha Conta</a></div></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p><p style="color:rgba(255,255,255,0.7);margin:8px 0 0 0;font-size:13px;">Transformando cada viagem em uma aventura inesquecível</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do cliente", "example": "Maria Santos"}, {"key": "portal_link", "label": "Link do portal", "example": "https://..."}]'),

-- Reserva e Pagamento
('reservation_confirmation', 'reservation_payment', 'Confirmação de Reserva', 'Enviado quando pagamento é aprovado', '✅ Reserva Confirmada - {{tour_nome}} | Camaleão Ecoturismo', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#820AD1 0%,#6B08A8 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">✅ Reserva Confirmada!</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Sua reserva foi confirmada com sucesso!</p><div style="background:#f8f8f8;border-radius:12px;padding:20px;margin:20px 0;"><p style="margin:8px 0;"><strong>Passeio:</strong> {{tour_nome}}</p><p style="margin:8px 0;"><strong>Data:</strong> {{tour_data}}</p><p style="margin:8px 0;"><strong>Participantes:</strong> {{num_participantes}}</p><p style="margin:8px 0;"><strong>Embarque:</strong> {{ponto_embarque}}</p><p style="margin:8px 0;"><strong>Valor:</strong> R$ {{valor_pago}}</p><p style="margin:8px 0;"><strong>Nº Reserva:</strong> {{reserva_numero}}</p></div><p style="color:#666;line-height:1.6;">📱 Criaremos um grupo no WhatsApp próximo à data da viagem com todos os detalhes!</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p><p style="color:rgba(255,255,255,0.7);margin:8px 0 0 0;font-size:13px;">Dúvidas? (82) 99364-9454</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do participante", "example": "João Silva"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "tour_data", "label": "Data do passeio", "example": "15 de Janeiro de 2025"}, {"key": "num_participantes", "label": "Número de participantes", "example": "2"}, {"key": "ponto_embarque", "label": "Ponto de embarque", "example": "Praça Central - 7h"}, {"key": "valor_pago", "label": "Valor pago", "example": "350,00"}, {"key": "reserva_numero", "label": "Número da reserva", "example": "RES20250110-0001"}]'),

('payment_pending', 'reservation_payment', 'Aguardando Pagamento PIX', 'Lembrete de PIX pendente', '⏳ Complete seu pagamento PIX - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#F9C74F 0%,#F9844A 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">⏳ Pagamento Pendente</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Notamos que seu pagamento PIX ainda está pendente. Complete para garantir sua vaga!</p><div style="background:#fff8e1;border-left:4px solid #F9C74F;padding:15px;margin:20px 0;"><p style="margin:0;color:#856404;"><strong>Valor:</strong> R$ {{valor}}</p><p style="margin:8px 0 0 0;color:#856404;"><strong>Expira em:</strong> {{expiry_time}}</p></div><p style="color:#999;font-size:14px;">Se você já realizou o pagamento, por favor desconsidere este e-mail.</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do cliente", "example": "Maria Santos"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "valor", "label": "Valor pendente", "example": "350,00"}, {"key": "expiry_time", "label": "Tempo até expirar", "example": "2 horas"}]'),

('payment_failed', 'reservation_payment', 'Pagamento Recusado', 'Notificação de falha no pagamento', '❌ Pagamento não aprovado - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#EF4444 0%,#DC2626 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">❌ Pagamento Não Aprovado</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Infelizmente seu pagamento não foi aprovado.</p><p style="color:#666;line-height:1.6;"><strong>Motivo:</strong> {{motivo}}</p><p style="color:#666;line-height:1.6;">Você pode tentar novamente com outro cartão ou via PIX.</p><div style="text-align:center;margin:30px 0;"><a href="{{retry_link}}" style="background:#820AD1;color:white;padding:16px 32px;text-decoration:none;border-radius:8px;font-weight:600;display:inline-block;">Tentar Novamente</a></div></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p><p style="color:rgba(255,255,255,0.7);margin:8px 0 0 0;font-size:13px;">Dúvidas? (82) 99364-9454</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do cliente", "example": "João Silva"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "motivo", "label": "Motivo da recusa", "example": "Saldo insuficiente"}, {"key": "retry_link", "label": "Link para tentar novamente", "example": "https://..."}]'),

-- Viagem e Logística
('trip_reminder_7days', 'trip_logistics', 'Lembrete 7 Dias', 'Lembrete enviado 7 dias antes da viagem', '📅 Faltam 7 dias para {{tour_nome}}!', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#820AD1 0%,#6B08A8 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">📅 Faltam 7 dias!</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Sua aventura está chegando! Não esqueça de preparar:</p><ul style="color:#666;line-height:1.8;"><li>Roupas confortáveis</li><li>Protetor solar e repelente</li><li>Água e lanches leves</li><li>Documento com foto</li></ul><div style="background:#f8f8f8;border-radius:12px;padding:20px;margin:20px 0;"><p style="margin:8px 0;"><strong>Data:</strong> {{tour_data}}</p><p style="margin:8px 0;"><strong>Embarque:</strong> {{ponto_embarque}}</p><p style="margin:8px 0;"><strong>Horário:</strong> {{horario}}</p></div></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do participante", "example": "Maria Santos"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "tour_data", "label": "Data do passeio", "example": "15 de Janeiro de 2025"}, {"key": "ponto_embarque", "label": "Ponto de embarque", "example": "Praça Central"}, {"key": "horario", "label": "Horário de embarque", "example": "7h00"}]'),

('trip_reminder_1day', 'trip_logistics', 'Lembrete Véspera', 'Lembrete enviado 1 dia antes da viagem', '🌅 Amanhã é o grande dia - {{tour_nome}}!', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#10B981 0%,#059669 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">🌅 Amanhã é o grande dia!</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Estamos muito animados! Aqui estão os últimos detalhes:</p><div style="background:#ecfdf5;border-left:4px solid #10B981;padding:15px;margin:20px 0;"><p style="margin:0;color:#065f46;font-weight:600;">📍 {{ponto_embarque}}</p><p style="margin:8px 0 0 0;color:#065f46;font-weight:600;">⏰ {{horario}}</p></div><p style="color:#666;line-height:1.6;"><strong>Dica:</strong> Chegue 10 minutos antes para não perder o embarque!</p><p style="color:#666;line-height:1.6;">Qualquer dúvida, entre em contato pelo WhatsApp.</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p><p style="color:rgba(255,255,255,0.7);margin:8px 0 0 0;font-size:13px;">(82) 99364-9454</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do participante", "example": "João Silva"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "ponto_embarque", "label": "Ponto de embarque", "example": "Praça Central"}, {"key": "horario", "label": "Horário de embarque", "example": "7h00"}]'),

('trip_info', 'trip_logistics', 'Informações da Viagem', 'Detalhes completos da viagem', '📋 Informações da sua viagem - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#820AD1 0%,#6B08A8 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">📋 Informações da Viagem</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Aqui estão todas as informações da sua viagem:</p><div style="background:#f8f8f8;border-radius:12px;padding:20px;margin:20px 0;">{{trip_details}}</div><h3 style="color:#333;margin:20px 0 10px 0;">O que levar:</h3><p style="color:#666;line-height:1.6;">{{what_to_bring}}</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do participante", "example": "Maria Santos"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "trip_details", "label": "Detalhes da viagem (HTML)", "example": "<p>Itinerário...</p>"}, {"key": "what_to_bring", "label": "O que levar", "example": "Protetor solar, água..."}]'),

('whatsapp_group_invite', 'trip_logistics', 'Convite Grupo WhatsApp', 'Link do grupo de WhatsApp da viagem', '📱 Grupo WhatsApp - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#25D366 0%,#128C7E 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">📱 Grupo WhatsApp</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;text-align:center;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">O grupo da viagem foi criado! Entre para receber atualizações e conhecer outros participantes:</p><div style="margin:30px 0;"><a href="{{group_link}}" style="background:#25D366;color:white;padding:16px 32px;text-decoration:none;border-radius:8px;font-weight:600;display:inline-block;">Entrar no Grupo</a></div><p style="color:#999;font-size:14px;">Este link é exclusivo para participantes confirmados.</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do participante", "example": "João Silva"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "group_link", "label": "Link do grupo", "example": "https://chat.whatsapp.com/..."}]'),

-- Cancelamento e Reembolso
('reservation_cancelled', 'cancellation_refund', 'Reserva Cancelada', 'Confirmação de cancelamento de reserva', '❌ Reserva Cancelada - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#6B7280 0%,#4B5563 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">❌ Reserva Cancelada</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Sua reserva foi cancelada conforme solicitado.</p><div style="background:#f8f8f8;border-radius:12px;padding:20px;margin:20px 0;"><p style="margin:8px 0;"><strong>Passeio:</strong> {{tour_nome}}</p><p style="margin:8px 0;"><strong>Data:</strong> {{tour_data}}</p><p style="margin:8px 0;"><strong>Motivo:</strong> {{motivo}}</p></div><p style="color:#666;line-height:1.6;">Esperamos vê-lo em breve em uma de nossas aventuras!</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do cliente", "example": "Maria Santos"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "tour_data", "label": "Data do passeio", "example": "15 de Janeiro de 2025"}, {"key": "motivo", "label": "Motivo do cancelamento", "example": "Solicitação do cliente"}]'),

('refund_full', 'cancellation_refund', 'Reembolso Total', 'Confirmação de reembolso total', '💰 Reembolso Processado - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#10B981 0%,#059669 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">💰 Reembolso Processado</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">Reembolso Total</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Seu reembolso foi processado com sucesso!</p><div style="background:#ecfdf5;border-left:4px solid #10B981;padding:15px;margin:20px 0;"><p style="margin:0;color:#065f46;font-weight:600;font-size:18px;">R$ {{valor_reembolso}}</p><p style="margin:8px 0 0 0;color:#065f46;">Prazo: até 7 dias úteis</p></div><p style="color:#666;line-height:1.6;">O valor será creditado na mesma forma de pagamento utilizada na compra.</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do cliente", "example": "João Silva"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "valor_reembolso", "label": "Valor do reembolso", "example": "350,00"}]'),

('refund_partial', 'cancellation_refund', 'Reembolso Parcial', 'Confirmação de reembolso parcial', '💰 Reembolso Parcial Processado - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#F59E0B 0%,#D97706 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">💰 Reembolso Parcial</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">Processado com Sucesso</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Seu reembolso parcial foi processado:</p><div style="background:#fffbeb;border-left:4px solid #F59E0B;padding:15px;margin:20px 0;"><p style="margin:0;color:#92400e;"><strong>Valor original:</strong> R$ {{valor_original}}</p><p style="margin:8px 0 0 0;color:#92400e;font-weight:600;font-size:18px;"><strong>Reembolsado:</strong> R$ {{valor_reembolso}}</p><p style="margin:8px 0 0 0;color:#92400e;">Prazo: até 7 dias úteis</p></div><p style="color:#666;line-height:1.6;"><strong>Motivo:</strong> {{motivo}}</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do cliente", "example": "Maria Santos"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "valor_original", "label": "Valor original", "example": "350,00"}, {"key": "valor_reembolso", "label": "Valor reembolsado", "example": "200,00"}, {"key": "motivo", "label": "Motivo do reembolso parcial", "example": "Política de cancelamento"}]'),

('tour_cancelled', 'cancellation_refund', 'Passeio Cancelado', 'Aviso de cancelamento do passeio pela empresa', '⚠️ Passeio Cancelado - {{tour_nome}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',Tahoma,Geneva,Verdana,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:40px 20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg,#EF4444 0%,#DC2626 100%);padding:40px;text-align:center;"><h1 style="color:white;margin:0 0 8px 0;font-size:28px;">⚠️ Passeio Cancelado</h1><p style="color:rgba(255,255,255,0.9);margin:0;font-size:16px;">{{tour_nome}}</p></td></tr><tr><td style="padding:40px;"><h2 style="color:#333;margin:0 0 16px 0;">Olá, {{nome}}!</h2><p style="color:#666;line-height:1.6;">Infelizmente precisamos cancelar o passeio <strong>{{tour_nome}}</strong> previsto para <strong>{{tour_data}}</strong>.</p><p style="color:#666;line-height:1.6;"><strong>Motivo:</strong> {{motivo}}</p><div style="background:#fef2f2;border-left:4px solid #EF4444;padding:15px;margin:20px 0;"><p style="margin:0;color:#991b1b;">O reembolso integral será processado automaticamente em até 7 dias úteis.</p></div><p style="color:#666;line-height:1.6;">Pedimos desculpas pelo transtorno e esperamos vê-lo em breve!</p></td></tr><tr><td style="background:#820AD1;padding:30px;text-align:center;"><p style="color:white;margin:0;font-size:16px;font-weight:600;">Camaleão Ecoturismo</p><p style="color:rgba(255,255,255,0.7);margin:8px 0 0 0;font-size:13px;">(82) 99364-9454</p></td></tr></table></td></tr></table></body></html>', '[{"key": "nome", "label": "Nome do cliente", "example": "João Silva"}, {"key": "tour_nome", "label": "Nome do passeio", "example": "Trilha das Cachoeiras"}, {"key": "tour_data", "label": "Data do passeio", "example": "15 de Janeiro de 2025"}, {"key": "motivo", "label": "Motivo do cancelamento", "example": "Condições climáticas adversas"}]');